### ISSUE TITLE
Spike: upgrade to Mimir feasibility check

### ISSUE THREAD

**Issue by schnidrig** [kubermatic/mla#138]
In March 2022 Grafana has announced Mimir as drop in replacement for Cortex: 

See : https://grafana.com/blog/2022/03/30/announcing-grafana-mimir/

From what they say, it sounds like this is where future development is to be expected.
The main differences currently are 
- better performance
- different license (AGPLv3 instead of Apache 2.0)

The high cardinality features sound like something one would appreciate in an environment where you can't control the data being send to the back end just like with the "User MLA of KKP".

**Comment by judge-red** [comment]
@csengerszabo Hi Csenger, I hope you don't mind the ping but I think/hope it's more efficient than going through support or sending you an email :) Not sure you remember, but we've talked about https://github.com/kubermatic/kubermatic/issues/10407 a while back (based on support ticket 3817).

I see that you're thinking about replacing Prometheus/promtail with Grafana Agent in KKP 2.22 (https://github.com/kubermatic/kubermatic/issues/10971), so I was wondering if you could take this into consideration as well. Or if not, tell us now so we know what we can expect to work with in the foreseeable future. We're not too opinionated about this (although with Grafana likely pulling their support out of Cortex, the latter might "die" fairly quickly, which is a concern) but would just like to know what to expect.

We're currently looking into enabling UC MLA for our customers (as we haven't previously found the time to evaluate the feature) and would rather wait for 2.22 if it includes such bigger changes than enable it now and then migrate in a few months. Cheers!

**Comment by csengerszabo** [comment]
@judge-red - first of all, some good news, we've just started working on https://github.com/kubermatic/kubermatic/issues/10407 and we plan adding it into our next minor.

About https://github.com/kubermatic/kubermatic/issues/10971, I tag @wurbanski here, as I am personally not aware of any previous consideration of replacing Cortex with Mimir.

**Comment by wurbanski** [comment]
I am closing this ticket and putting this task in the backlog as kubermatic/kubermatic#11364.

Summary here for everyone involved: while Mimir is a drop-in replacement for cortex in a vacuum, we would have to adjust the configuration in a few ways to make it compatible with our controllers. Also, as a part of KKP, we will have to provide safe and automated migration path between the solutions.
