### ISSUE TITLE
Add UserCluster MLA installation to kkp installer

### ISSUE THREAD

**Issue by wurbanski** [kubermatic/mla#139]
- [ ] Move helm charts from kubermatic/mla repo to kubermatic/kubermatic
- [ ] Implement installation process in the kkp installer
- [ ] create documentation

**Comment by ahmedwaleedmalik** [comment]
@wurbanski do we really need to move helm charts to the KKP repo? Would an umbrella chart for MLA suit our use case?

**Comment by wurbanski** [comment]
@ahmedwaleedmalik we want to get rid of the second repository so we have to do it some way. Umbrella chart might be it, but it would change the installation for the end users a bit - we will see.

**Comment by judge-red** [comment]
Can I ask whether upgrading the chart versions and keeping them up to date afterwards is also part of moving UC MLA to the kubermatic-installer / main repo? The current versions are all from last November and quite something happened upstream. With the current installation method, we can opt for newer versions fairly easily, but that flexibility will be gone if the installation is performed by the kubermatic-installer, which would be a major drawback if they're not kept up to date with new (minor) releases of KKP in future.

**Comment by wurbanski** [comment]
@judge-red Yes, that's part of the effort of maturing the User Cluster MLA as well. 

It's a fair point about the stack components not being up to date and it's something we will be improving as we move the UserCluster MLA out of experimental stage.

BTW. using kubermatic-installer still allows you to make changes to the configuration of the helm deployments as needed, including upgrading the versions if need be.
