### ISSUE TITLE
poddisruptionbudgets and seed node rollout

### ISSUE THREAD

**Issue by dharapvj** [kubermatic/mla#83]
with the poddisruptionbudgets in place, the worker node rollout for seeds gets stuck because nodes cannot get drained as draining the nodes would breach the disruption budgets specified for consule and loki-distributor pods.

We need to tweak the budgets so that nodes can get rolled over properly

**Comment by wurbanski** [comment]
The issue couldn't be reproduced with default settings in clusters with >= 3 nodes. I will close it for now, but please reopen if you find that it happens again. We would require more details regarding the environment where it happens.
