### ISSUE TITLE
upgrade deleted minio secret and makes entire stack unusable

### ISSUE THREAD

**Issue by dharapvj** [kubermatic/mla#84]
When we upgraded MLA stack from commit f6cc26f3efbaa86eefa8f128c073ecaa9cdd56d5 to commit 1a033b8ec6fc1a23ca2ca79775ced143a410e206, helm proceeded to delete minio secret and thereby entire stack became unusable.

We had to hack around history of helm to recover the secret and re-create it manually.

upgrade process should be stable or we should mention this is as a breaking change and ask user to backup the minio secret before upgrade.

**Comment by wurbanski** [comment]
commit https://github.com/kubermatic/mla/commit/ab5996a2c4629a73fcc4f11314623e8b19c20bbe from August removed the secret re-deployment so this situation shouldn't have happened. I think that maybe wrong/edited version of the deploy script has been used.

https://docs.kubermatic.com/kubermatic/v2.20/tutorials_howtos/monitoring_logging_alerting/user_cluster/admin_guide/#installing-mla-stack-in-a-seed-cluster documentation specifically mentions running this before installing the MLA (not upgrading). It also specifies how to skip creating a secret.
